language: node_js
node_js:
  - "node"
cache:
  - npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "match-birthdays"
  region: eu-west-1
  acl: public_read